version: '3.4'

services:
  client:
    image: pcall
    platform: linux/amd64
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
