name: Runs Vitest unit tests

on:
  push:
    branches: [ "105-implement-e2e-tests" ]
  pull_request:
    branches: [ "105-implement-e2e-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Execute Unit tests
    - run: npm ci
    - run: npm run test:unit
